// QuickKOL V1 internal sponsorship benchmarks, not advertising-platform CPMs.
export const rateConfig = {
  platforms: {
    tiktok: { label: 'TikTok', cpm: 10, minimum: 100, engagement: [[2, 0.85], [4, 1], [7, 1.10], [10, 1.18], [Infinity, 1.25]] },
    instagram: { label: 'Instagram', cpm: 15, minimum: 100, engagement: [[1, 0.85], [3, 1], [5, 1.10], [8, 1.18], [Infinity, 1.25]] },
    youtube: { label: 'YouTube', cpm: 60, minimum: 150, engagement: [[2, 0.90], [4, 1], [6, 1.10], [10, 1.18], [Infinity, 1.25]] },
    x: { label: 'X / Twitter', cpm: 5, minimum: 75, engagement: [[0.5, 0.85], [1.5, 1], [3, 1.10], [5, 1.18], [Infinity, 1.25]] },
  },
  followerMultipliers: [[10000, 0.90], [50000, 1], [100000, 1.03], [500000, 1.07], [1000000, 1.12], [5000000, 1.18], [Infinity, 1.25]],
  countryMultipliers: {
    us: { flag: '🇺🇸', label: ['美国', 'United States'], multiplier: 1 },
    ch: { flag: '🇨🇭', label: ['瑞士', 'Switzerland'], multiplier: 1 },
    gb: { flag: '🇬🇧', label: ['英国', 'United Kingdom'], multiplier: 0.9 },
    au: { flag: '🇦🇺', label: ['澳大利亚', 'Australia'], multiplier: 0.85 },
    ca: { flag: '🇨🇦', label: ['加拿大', 'Canada'], multiplier: 0.85 },
    de: { flag: '🇩🇪', label: ['德国', 'Germany'], multiplier: 0.8 },
    fr: { flag: '🇫🇷', label: ['法国', 'France'], multiplier: 0.75 },
    nl: { flag: '🇳🇱', label: ['荷兰', 'Netherlands'], multiplier: 0.8 },
    se: { flag: '🇸🇪', label: ['瑞典', 'Sweden'], multiplier: 0.85 },
    sg: { flag: '🇸🇬', label: ['新加坡', 'Singapore'], multiplier: 0.85 },
    ae: { flag: '🇦🇪', label: ['阿联酋', 'United Arab Emirates'], multiplier: 0.8 },
    jp: { flag: '🇯🇵', label: ['日本', 'Japan'], multiplier: 0.75 },
    kr: { flag: '🇰🇷', label: ['韩国', 'South Korea'], multiplier: 0.7 },
    it: { flag: '🇮🇹', label: ['意大利', 'Italy'], multiplier: 0.7 },
    es: { flag: '🇪🇸', label: ['西班牙', 'Spain'], multiplier: 0.65 },
    pl: { flag: '🇵🇱', label: ['波兰', 'Poland'], multiplier: 0.55 },
    br: { flag: '🇧🇷', label: ['巴西', 'Brazil'], multiplier: 0.45 },
    mx: { flag: '🇲🇽', label: ['墨西哥', 'Mexico'], multiplier: 0.45 },
    cn: { flag: '🇨🇳', label: ['中国', 'China'], multiplier: 0.45 },
    my: { flag: '🇲🇾', label: ['马来西亚', 'Malaysia'], multiplier: 0.4 },
    th: { flag: '🇹🇭', label: ['泰国', 'Thailand'], multiplier: 0.4 },
    vn: { flag: '🇻🇳', label: ['越南', 'Vietnam'], multiplier: 0.35 },
    id: { flag: '🇮🇩', label: ['印度尼西亚', 'Indonesia'], multiplier: 0.35 },
    ph: { flag: '🇵🇭', label: ['菲律宾', 'Philippines'], multiplier: 0.35 },
    in: { flag: '🇮🇳', label: ['印度', 'India'], multiplier: 0.3 },
    pk: { flag: '🇵🇰', label: ['巴基斯坦', 'Pakistan'], multiplier: 0.25 },
    ng: { flag: '🇳🇬', label: ['尼日利亚', 'Nigeria'], multiplier: 0.3 },
    other: { flag: '🌍', label: ['其他国家 / 地区', 'Other'], multiplier: 0.65 },
  },
  audienceMultipliers: {
    low: { label: ['较低', 'Low'], multiplier: 0.85 },
    average: { label: ['一般', 'Average'], multiplier: 1 },
    high: { label: ['较高', 'High'], multiplier: 1.20 },
  },
  contentMultipliers: {
    basic: { label: ['基础', 'Basic'], multiplier: 0.85 },
    good: { label: ['良好', 'Good'], multiplier: 1 },
    premium: { label: ['优质', 'Premium'], multiplier: 1.20 },
  },
  nicheMultipliers: {
    default: { icon: '', label: ['默认', 'Default'], multiplier: 1 },
    entertainment: { icon: 'mask-happy', label: ['娱乐', 'Entertainment'], multiplier: 0.90 },
    lifestyle: { icon: 'house', label: ['生活方式', 'Lifestyle'], multiplier: 1 },
    fashion: { icon: 't-shirt', label: ['时尚', 'Fashion'], multiplier: 1.1 },
    beauty: { icon: 'sparkle', label: ['美妆', 'Beauty'], multiplier: 1.1 },
    gaming: { icon: 'game-controller', label: ['游戏', 'Gaming'], multiplier: 1 },
    foodTravel: { icon: 'fork-knife', label: ['美食 / 旅行', 'Food / Travel'], multiplier: 1 },
    fitness: { icon: 'barbell', label: ['健身 / 健康', 'Fitness / Wellness'], multiplier: 1.1 },
    education: { icon: 'graduation-cap', label: ['教育', 'Education'], multiplier: 1.1 },
    tech: { icon: 'laptop', label: ['科技 / AI', 'Tech / AI'], multiplier: 1.2 },
    business: { icon: 'briefcase', label: ['商业 / SaaS', 'Business / SaaS'], multiplier: 1.2 },
    finance: { icon: 'currency-dollar', label: ['金融', 'Finance'], multiplier: 1.20 },
    other: { icon: 'dots-three', label: ['其他', 'Other'], multiplier: 1 },
  },
  rangeMultiplier: { low: 0.80, high: 1.20 },
  rounding: [{ min: 1000, step: 100 }, { min: 100, step: 10 }, { min: 0, step: 5 }],
};
